version: 0.0.6.{build}

platform:
    - x64

environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37-x64"

install:
  - cmd: "%PYTHON%\\python.exe -m pip install numpy"
  - ps: Invoke-RestMethod https://github.com/ELIFE-ASU/Inform/releases/download/v1.0.0/inform-1.0.0_mixed.zip -OutFile inform-1.0.0_mixed.zip
  - ps: 7z x inform-1.0.0_mixed.zip
  - ps: Move-Item inform-1.0.0 pyinform/inform-1.0.0
  - ps: Remove-Item inform-1.0.0_mixed.zip
  - cmd: "%PYTHON%\\python.exe -m pip install ."

build: off

test_script:
  - "%PYTHON%\\python.exe -m unittest"
