language: python

os:
    - linux
    # - osx

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - wget https://github.com/ELIFE-ASU/Inform/releases/download/v1.0.0/inform-1.0.0_mixed.zip
  - unzip inform-1.0.0_mixed.zip
  - mv inform-1.0.0 pyinform/inform-1.0.0
  - rm inform-1.0.0_mixed.zip
  - pip install .
  - pip install codecov

script:
  - python setup.py test
  - codecov
